# Generated by Django 5.1 on 2024-08-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_idea_email_remove_idea_favorite_dish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='email',
            field=models.EmailField(default=' ', max_length=254),
        ),
        migrations.AddField(
            model_name='idea',
            name='favorite_dish',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='idea',
            name='name',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='idea',
            name='content',
            field=models.TextField(default=' '),
        ),
    ]
