# Generated by Django 5.1 on 2024-08-23 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_idea_content_alter_idea_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='email',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='favorite_dish',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='name',
        ),
    ]
