# Generated by Django 5.1 on 2024-08-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_interestedperson_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestedperson',
            name='email',
            field=models.TextField(),
        ),
    ]
